# Generated by Django 3.2.4 on 2021-08-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=17)),
                ('description', models.CharField(max_length=20)),
                ('date_of_event', models.DateField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('duration', models.DateField()),
            ],
        ),
    ]
