# Generated by Django 3.2.4 on 2021-08-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0002_alter_trainer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
