# Generated by Django 3.2.4 on 2021-08-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=18)),
                ('Trainer', models.CharField(max_length=19)),
                ('Course_code', models.IntegerField()),
                ('description', models.TextField(max_length=70)),
            ],
        ),
    ]
