# Generated by Django 3.2.4 on 2021-08-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_code',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course_name',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Trainer',
            new_name='trainer',
        ),
    ]
