# Generated by Django 3.2.4 on 2021-08-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=16)),
                ('trainer_id', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'female'), ('m', 'male'), ('o', 'other')], max_length=16)),
                ('company', models.CharField(max_length=18)),
                ('resume', models.FileField(upload_to='')),
                ('salary', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('contract', models.FileField(upload_to='')),
            ],
        ),
    ]
