# Generated by Django 3.2.4 on 2021-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainer', '0003_auto_20210830_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
