# Generated by Django 3.2.4 on 2021-08-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.CharField(max_length=200),
        ),
    ]
