# Generated by Django 3.2.4 on 2021-08-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
