# Generated by Django 3.2.4 on 2021-08-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210825_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
